### ISSUE TITLE
Good work! 

### ISSUE THREAD

**Issue by jiangerxiaozhao** [ispc-lab/ACM-Net#1]
Good work! THUMOS-14 can be reproduced, but ActivityNet-1.3 can't? Any Suggestions?

Current test_mAP:0.2228, Current Best test_mAP:0.2342 Current Epoch:954/1000

**Comment by sanqingqu** [comment]
Sorry for the late reply, as the ActivityNet-1.3 is a much more diverse and complex dataset compared to the THUMOS-14. In fact, we have included some stricter regularization tricks in the training process, which I have dropped in this open-source version to keep the code simple. I will update the codebase with these tricks as soon as possible.

**Comment by sanqingqu** [comment]
I have updated the codes, you can try it again!
