### ISSUE TITLE
How to visualize the picture of temporal feature?

### ISSUE THREAD

**Issue by CHI-YU-SUNG** [ispc-lab/ACM-Net#3]
![image](https://user-images.githubusercontent.com/51199659/133888611-c25f96f8-3cbf-4cb2-a36d-f7ebcbf607a4.png)
Is there any tutorial or code from model feature( i3d) to the temporal visualization

**Comment by sanqingqu** [comment]
Thanks for your interest in our work. In fact, this picture is based on the three-branch attention values, and we utilize the `plt.hist2d` function to realize the visualization purpose.

**Comment by CHI-YU-SUNG** [comment]
Thanks for answer the question, it help a lot.
