### ISSUE TITLE
results reproduce on THUMOS-14 

### ISSUE THREAD

**Issue by baiyang4** [ispc-lab/ACM-Net#5]
Hi there,

Thanks for your great work! I'm really interested and trying to follow your work.
However, during reproducing resutls on THUMOS-14, I only got 0.336 after 1000 epochs using GPU 3090.
I just clone the code from this repo and changed nothing. I downloaded data followed the link provided in this repo.
Do you have any clue on this?
Looking forward to yoru reply.

BW

**Comment by sanqingqu** [comment]
Hi, baiyang!

Thanks for your interest in our ACM-Net. In fact, we also utilize the 3090 GPU platform to develop this project. So your reproducing results should be similar to ours. It is worth noting that the mAP metrics we reported during the training period for the THUMOS-14 dataset were averaged over `tIOU 0.1-0.9`, and they were not converted to centiles. You can modify this param in the `config/model_config.py`.

**Comment by baiyang4** [comment]
Hi Sanqing,

Thanks for your quick reply! 
Do you mean I need to change the `tIOU` from 0.1-0.9 to 0.1-0.7?

**Comment by sanqingqu** [comment]
Yes! It should work.
