### ISSUE TITLE
Hi,I found the number of ActivityNet's feature is different from the number of video(9032vs10024 in train,4427vs5044 in test),is there any explaination about these absence features?

### ISSUE THREAD

**Issue by pipixin321** [ispc-lab/ACM-Net#6]

**Comment by sanqingqu** [comment]
Hi there, 
The main reason for this is that the ActivityNet dataset, like Kinetics-400 and Kinetics-600, is composed of a series of Youtube videos.  For the convenience of data transfer, the dataset authors only disclose the link addresses of the corresponding videos, not the original stored data. However, for some reason, some of the video links in the ActivityNet dataset are not working, so the actual data available to us is not the same size as the original dataset.
