### ISSUE TITLE
关于在THUMOS上的复现问题

### ISSUE THREAD

**Issue by LaynZ** [ispc-lab/ACM-Net#7]

**Comment by LaynZ** [comment]
你好  我在THUMOS上在不修改任何参数的情况下在map0.5下只能复现到30左右，当我去掉feat loss与spare loss后又可以达到32.5左右，当我只降低学习率的时候又可以达到33左右  请问有什么办法可以解决这个问题吗  我想复现到34.6

**Comment by sanqingqu** [comment]
Thank you for your interest in our work. I think the main possible reason is that we have different computing platforms and operating environments. Our work is based on Ubuntu 20.04 and RTX 3090. You could try our platform and python environment. Or, you can directly report the results of our paper on THU-14.

**Comment by LaynZ** [comment]
好的  十分感谢
